# Generated by Django 4.0.1 on 2022-05-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211130_0929'),
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
    ]
